/* # 채용공고등록 테이블

*/

/* # 개인회원 테이블 
CREATE TABLE USERS(
		USER_ID VARCHAR2(200) NOT NULL PRIMARY KEY
	,	USER_PW VARCHAR2(200) NOT NULL 
	, 	USER_PHONE VARCHAR2(200) NOT NULL 
	,	USER_BIRTH VARCHAR2(200) NOT NULL
	,	USER_EMAIL VARCHAR2(500) NOT NULL
	,	USER_ADDRESS VARCHAR2(1000)
	,	USER_NAME VARCHAR2(200)
	,   USER_ROLE VARCHER2(20)
);
*/


/*
**** 개인회원 테이블 임시 ****
--회원 테이블
CREATE TABLE USER_TABLE (
USER_ID VARCHAR2(20) NOT NULL  -- 회원 아이디
, USER_PW VARCHAR2(100) NOT NULL -- 회원 비밀번호
, USER_PHONE VARCHAR2(11)NOT NULL -- 회원 전화번호
, USER_BIRTH TIMESTAMP NOT NULL  -- 회원 생년월일
, USER_EMAIL VARCHAR2(254) NOT NULL  -- 회원 이메일
, USER_ADRESS VARCHAR2(100)  --회원 주소
, USER_NAME VARCHAR2(50)-- 회원 이름
, USER_BUSINESS_TYPE VARCHAR2(200)  --회원업종
, USER_BUSINESS_LICENSE VARCHAR2(200)  -- 회원 사업자번호
, USER_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP --계정 생성일시
, USER_LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- 마지막 로그인 일시
, USER_COUNT NUMBER -- 총 방문횟수
, USER_ACT VARCHAR2(1) CHECK (USER_ACT IN('Y', 'N')) -- 계정 활성화
, USER_ROLE VARCHAR2(2) CHECK (USER_ROLE IN('B', 'P','A','AM')) -- 회원 분류
, TERMS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- 약관 동의 일시
, TERMS_PERIOD NUMBER NOT NULL-- 약관 동의기간
, TERMS_ACT VARCHAR2(1) NOT NULL CHECK (TERMS_ACT IN('Y', 'N'))-- 약관 동의유무
);


-- 이력서 테이블
CREATE TABLE USER_RESUME (
    RESUME_NO NUMBER NOT NULL PRIMARY KEY -- 이력서 고유번호
    , USER_ID VARCHAR2(20) NOT NULL  -- 회원 아이디 
    , RESUME_TITLE VARCHAR2(60) NOT NULL  -- 이력서 제목
    , RESUME_PHOTO VARCHAR2(200)  -- 이력서 사진(파일)
    , H_EDU_NO NUMBER  -- 고등학교 학력사항 고유번호
    , U_EDU_NO NUMBER  -- 대학교 학력사항 고유번호
    , G_EDU_NO NUMBER  -- 대학원 경력사항 고유번호
    , CAR_NO NUMBER  -- 경력사항 고유번호
    , CERTI_NO NUMBER  -- 자격증 고유번호
    , CL_NO NUMBER  -- 자기소개서 고유번호
    , RESUME_ACT VARCHAR2(1) -- 이력서 공개 여부 
    , RESUME_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- 이력서 작성 일시 
    , PORTF_FILE VARCHAR2(200) -- 포트폴리오(파일)
);

DROP TABLE USER_RESUME;

-- 고등학교 학력사항
CREATE TABLE R_HSCHOOL(
    H_EDU_NO NUMBER NOT NULL PRIMARY KEY 
    , GED VARCHAR2(1) CHECK (GED IN('Y', 'N')) DEFAULT 'N'
    , H_ACT VARCHAR2(1) CHECK (H_ACT IN('Y', 'N')) DEFAULT 'Y'
    , H_NAME VARCHAR2(60)
    , H_DATE TIMESTAMP
    , H_MAJOR VARCHAR2(10)
    , USER_ID VARCHAR2(20) NOT NULL
);  


-- 대학교 학력사항
CREATE TABLE R_UNIVERSITY(
U_EDU_NO NUMBER NOT NULL   PRIMARY KEY -- 대학교 학력사항 고유번호
, U_ACT VARCHAR2(1) NOT NULL CHECK (U_ACT IN('Y', 'N', 'R', 'X')) --대학교 졸업유무
, U_CATEGORY VARCHAR2(1) CHECK (U_CATEGORY IN('T', 'F'))  -- 대학 카테고리 
, U_NAME VARCHAR2(30) -- 대학 명 
, U_DATE TIMESTAMP  -- 대학 재학기간
, U_MAJOR VACHAR2(45)  --대학 전공
, U_POINT DOUBLE(5,2)  -- 대학 학점
, USER_ID VARCHAR2(20) NOT NULL);  --회원 아이디



-- 대학원 학력사항
CREATE TABLE R_GSCHOOL(
G_EDU_NO NUMBER NOT NULL   PRIMARY KEY  -- 대학교 학력사항 고유번호
, G_ACT VARCHAR2(1) NOT NULL CHECK (U_ACT IN('Y', 'N', 'R', 'X')) -- 대학원 졸업유무
, G_NAME VARCHAR2(30) --대학원명
, G_CATEGORY CHAR(6) -- 석/박사
, G_DATE TIMESTAMP -- 대학원 재학기간
, G_MAJOR VACHAR2(45)  -- 대학원 전공
, G_POINT DOUBLE(5,2)  -- 대학원 학점
, USER_ID VARCHAR2(20) NOT NULL  --회원 아이디
);


-- 경력사항
CREATE TABLE R_CAREER(
CAR_NO NUMBER NOT NULL   PRIMARY KEY
, CAR_ACT VARCHAR2(1) NOT NULL CHECK (CAR_ACT IN('Y', 'N')) -- 경력 유무
, CAR_NAME VARCHAR2(100)  -- 회사명
, CAR_DATE TIMESTAMP  -- 재직기간
, CAR_POSITION VACHAR2(50)  -- 직급/직책
, CAR_DEPT VACHAR2(50)  -- 근무부서
, CAR_RESP VACHAR2(200)  -- 담당업무
, CAR_SALARY NUMBER  -- 연봉
, USER_ID VARCHAR2(20) NOT NULL  --회원 아이디
);


-- 자격증
CREATE TABLE R_CERTI(
CERTI_NO NUMBER NOT NULL   PRIMARY KEY -- 자격증 고유번호
, CERTI_ACT NOT NULL CHECK (CERTI_ACT IN('Y', 'N'))  -- 자격증 유무 
, CERTI_NAME VARCHAR2(100)  -- 자격증명
, CERTI_PUB VARCHAR2(100)  -- 자격증 발행처
, CERTI_DATE TIMESTAMP  -- 자격증 취득일자
, USER_ID VARCHAR2(20) NOT NULL  --회원 아이디
);


-- 자기소개서
CREATE TABLE R_CL(
, CL_NO NUMBER NOT NULL   PRIMARY KEY -- 자기소개서 고유번호
, CL_FILE VACHAR2(200)  -- 자기소개서 파일
, CL_GROWTH CLOB  -- 자기소개서 성장과정
, CL_MOTIVE CLOB  -- 자기소개서 지원동기
, CL_ADV CLOB  -- 자기소개서 장단점
, CL_ASP CLOB  -- 자기소개서 입사후 포부
, USER_ID VARCHAR2(20) NOT NULL  --회원 아이디
);


-- 개인회원 지원
CREATE TABLE USER_APPLY(
, USER_ID VARCHAR2(20) NOT NULL   PRIMARY KEY --회원 아이디
, RA_NUM NUMBER NOT NULL -- 공고번호
, APPLY DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- 지원일자
);

*/




-- 카테고리 테이블 
DROP TABLE "JA_CATEGORY";

CREATE TABLE "JA_CATEGORY" (
	"CATEGORY_ID"	VARCHAR2(20)		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(50)		NOT NULL,
	"CATEGORY_DEPT"	VARCHAR2(10)		NULL,
	"CATEGORY_TYPE"	VARCHAR2(50)		NULL,
	"REQ_CATEGORY_ID"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "JA_CATEGORY"."CATEGORY_ID" IS 'ID 시퀀스로 순차 증가 (임시)';

COMMENT ON COLUMN "JA_CATEGORY"."CATEGORY_TYPE" IS '해당 ROW의 카테고리 고유번호를 대표하는 데이터';

COMMENT ON COLUMN "JA_CATEGORY"."REQ_CATEGORY_ID" IS '참조하는 상위단계 아이디';

ALTER TABLE "JA_CATEGORY" ADD CONSTRAINT "PK_JA_CATEGORY" PRIMARY KEY (
	"CATEGORY_ID"
);


